export {
	type UamAnimationGearBinding,
	type UamAnimationGearValue,
	type UamAssetResource,
	type UamAssetResourceKind,
	type UamColorGearBinding,
	type UamColorGearValue,
	type UamComponentModel,
	type UamComponentRefNode,
	type UamComponentResource,
	type UamControllerAction,
	type UamControllerModel,
	type UamControllerPage,
	type UamDimensions,
	type UamDisplay2GearBinding,
	type UamDisplayGearBinding,
	type UamDisplayNode,
	type UamDisplayNodeKind,
	type UamEdgeInsets,
	type UamFontSizeGearBinding,
	type UamFontSizeGearValue,
	type UamGearBinding,
	type UamGearPageState,
	type UamGraphNode,
	type UamGroupNode,
	type UamIconGearBinding,
	type UamIconGearValue,
	type UamImageNode,
	type UamListItemData,
	type UamListNode,
	type UamLoader3DNode,
	type UamLoaderNode,
	type UamLookGearBinding,
	type UamLookGearValue,
	type UamMovieClipNode,
	type UamPackage,
	type UamPackagePublish,
	type UamPoint,
	type UamProject,
	type UamRelation,
	type UamResource,
	type UamResourceRef,
	type UamRichTextNode,
	type UamSize,
	type UamSizeGearBinding,
	type UamSizeGearValue,
	type UamTextGearBinding,
	type UamTextGearValue,
	type UamTextInputNode,
	type UamTextNode,
	type UamTreeNode,
	type UamTransitionItem,
	type UamTransitionModel,
	type UamValidationIssue,
	type UamXYGearBinding,
	type UamXYGearValue,
	UAM_SUPPORTED_MATERIALIZATION_SCOPE,
	UAM_SUPPORTED_TRANSACTION_SCOPE,
} from './model.js';
export { normalizeUamProject } from './normalize.js';
export { assertValidUamProject, validateUamProject } from './validate.js';
export { liftDocumentToUamProject, materializeUamProject, readProjectAsUam, writeProjectFromUam } from './bridge.js';
export {
	UamTransaction,
	UamTransactionError,
	type UamComponentSelector,
	type UamControllerSelector,
	type UamDisplayNodePropsUpdate,
	type UamDisplayNodeSelector,
	type UamLookGearSelector,
	type UamResourceSelector,
	type UamTransactionErrorCode,
	type UamTransactionOperation,
	type UamTransactionSupportIssue,
	type UamTransitionSelector,
	applyUamTransaction,
	assertTransactionSupported,
	createUamTransaction,
	validateTransactionSupport,
} from './transaction.js';
