export {
	type UamAnimationGearBinding,
	type UamAnimationGearValue,
	type UamAssetResource,
	type UamAssetResourceKind,
	type UamButtonNode,
	type UamBlendMode,
	type UamColorGearBinding,
	type UamColorGearValue,
	type UamComboBoxNode,
	type UamComponentCustomProperty,
	type UamComponentInstanceComboItem,
	type UamComponentInstanceProperties,
	type UamComponentModel,
	type UamComponentProperties,
	type UamComponentRefNode,
	type UamComponentResource,
	type UamControllerAction,
	type UamControllerModel,
	type UamControllerPage,
	type UamDimensions,
	type UamDisplay2GearBinding,
	type UamDisplayGearBinding,
	type UamDisplayNode,
	type UamDisplayNodeBase,
	type UamDisplayNodeKind,
	type UamEdgeInsets,
	type UamFontSizeGearBinding,
	type UamFontSizeGearValue,
	type UamGearBinding,
	type UamGearPageState,
	type UamGenericAssetResource,
	type UamGraphNode,
	type UamGraphProperties,
	type UamGroupNode,
	type UamGroupProperties,
	type UamGroupableDisplayNodeBase,
	type UamIconGearBinding,
	type UamIconGearValue,
	type UamImageNode,
	type UamImageResource,
	type UamImageResourceProperties,
	type UamLabelNode,
	type UamListItemData,
	type UamListNode,
	type UamListProperties,
	type UamLoader3DNode,
	type UamLoader3DProperties,
	type UamLoaderNode,
	type UamLoaderProperties,
	type UamLookGearBinding,
	type UamLookGearValue,
	type UamMovieClipNode,
	type UamPackage,
	type UamPackagePublish,
	type UamPoint,
	type UamProgressBarNode,
	type UamProject,
	type UamRelation,
	type UamResource,
	type UamResourceRef,
	type UamRichTextNode,
	type UamScrollBarNode,
	type UamSize,
	type UamSizeGearBinding,
	type UamSizeGearValue,
	type UamSliderNode,
	type UamPlainTextProperties,
	type UamTextGearBinding,
	type UamTextGearValue,
	type UamTextInputNode,
	type UamTextNode,
	type UamTextProperties,
	type UamTreeNode,
	type UamTreeProperties,
	type UamTransitionItem,
	type UamTransitionModel,
	type UamValidationIssue,
	type UamXYGearBinding,
	type UamXYGearValue,
	UAM_SUPPORTED_MATERIALIZATION_SCOPE,
	UAM_SUPPORTED_TRANSACTION_SCOPE,
} from './model.js';
export {
	createDefaultUamComponentProperties,
	createDefaultUamImageResourceProperties,
	createDefaultUamPlainTextProperties,
	createDefaultUamTextProperties,
	normalizeUamProject,
} from './normalize.js';
export { assertValidUamProject, validateUamProject } from './validate.js';
export {
	commitUamProjectSourcePaths,
	liftDocumentToUamProject,
	materializeUamProject,
	readProjectAsUam,
	type WriteProjectFromUamOptions,
	writeProjectFromUam,
} from './bridge.js';
export {
	type AddComponentOperation,
	type AddGearOperation,
	type AddPackageOperation,
	type AddResourceOperation,
	type MoveComponentOperation,
	type RemoveComponentOperation,
	type RemoveGearOperation,
	type RemovePackageOperation,
	type RemoveResourceOperation,
	type RenamePackageOperation,
	type SetComponentPropsOperation,
	type SetImageResourcePropsOperation,
	type SetResourceFavoriteOperation,
	type ReplaceResourceBytesOperation,
	UamTransaction,
	UamTransactionError,
	type UamComponentSelector,
	type UamControllerSelector,
	type UamDisplayNodePropsUpdate,
	type UamDisplayNodeSelector,
	type UamGearSelector,
	type UamLookGearSelector,
	type UamPackageSelector,
	type UamResourceSelector,
	type UamTransactionErrorCode,
	type UamTransactionOperation,
	type UamTransactionSupportIssueCode,
	type UamTransactionSupportIssue,
	type UamTransitionSelector,
	type UpdateGearOperation,
	applyUamTransaction,
	assertTransactionSupported,
	createUamTransaction,
	validateTransactionSupport,
} from './transaction.js';
