export {
	type UamAnimationGearBinding,
	type UamAnimationGearValue,
	type UamAssetResource,
	type UamAssetResourceKind,
	type UamColorGearBinding,
	type UamColorGearValue,
	type UamComponentModel,
	type UamComponentRefNode,
	type UamComponentResource,
	type UamControllerAction,
	type UamControllerModel,
	type UamControllerPage,
	type UamDimensions,
	type UamDisplay2GearBinding,
	type UamDisplayGearBinding,
	type UamDisplayNode,
	type UamDisplayNodeKind,
	type UamFontSizeGearBinding,
	type UamFontSizeGearValue,
	type UamGearBinding,
	type UamGearPageState,
	type UamIconGearBinding,
	type UamIconGearValue,
	type UamImageNode,
	type UamLookGearBinding,
	type UamLookGearValue,
	type UamPackage,
	type UamPackagePublish,
	type UamPoint,
	type UamProject,
	type UamRelation,
	type UamResource,
	type UamResourceRef,
	type UamSize,
	type UamSizeGearBinding,
	type UamSizeGearValue,
	type UamTextGearBinding,
	type UamTextGearValue,
	type UamTextNode,
	type UamTransitionItem,
	type UamTransitionModel,
	type UamValidationIssue,
	type UamXYGearBinding,
	type UamXYGearValue,
	UAM_SUPPORTED_MATERIALIZATION_SCOPE,
} from './model.js';
export { normalizeUamProject } from './normalize.js';
export { assertValidUamProject, validateUamProject } from './validate.js';
export { liftDocumentToUamProject, materializeUamProject, readProjectAsUam, writeProjectFromUam } from './bridge.js';
